/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 computer.gltf --transform 
Files: computer.gltf [2.42MB] > C:\Users\Elija\Documents\toy_desktop_computer\computer-transformed.glb [1.03MB] (57%)
Author: EVA-Stud (https://sketchfab.com/EVAStud)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toy-desktop-computer-49dc499a779e404d8aac9ae3ea3b63f1
Title: toy desktop computer
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/computer-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.009}>
          <group name="Circle" position={[-112.847, -83.787, 0]} scale={15.39}>
            <mesh
              name="Circle_Material002_0"
              geometry={nodes.Circle_Material002_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group name="Circle001" position={[126.7, -94.005, 0]} scale={28.331}>
            <mesh
              name="Circle001_Material002_0"
              geometry={nodes.Circle001_Material002_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group
            name="Circle002"
            position={[157.131, -80.207, -4.551]}
            scale={19.782}
          >
            <mesh
              name="Circle002_Material002_0"
              geometry={nodes.Circle002_Material002_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group
            name="Circle004"
            position={[126.878, -67.996, -2.736]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.81}
          >
            <group
              name="Circle003"
              position={[0.519, 0.043, 67.728]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={26.655}
            >
              <mesh
                name="Circle003_BMD_AbstractGlass001_0"
                geometry={nodes.Circle003_BMD_AbstractGlass001_0.geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
            <mesh
              name="Circle004_Material009_0"
              geometry={nodes.Circle004_Material009_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group
            name="Circle005"
            position={[156.851, -63.603, -7.009]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.81}
          >
            <group
              name="Circle006"
              position={[0.243, 0.251, 48.465]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[19.003, 19.003, 11.226]}
            >
              <mesh
                name="Circle006_BMD_AbstractGlass001_0"
                geometry={nodes.Circle006_BMD_AbstractGlass001_0.geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
            <mesh
              name="Circle005_Material009_0"
              geometry={nodes.Circle005_Material009_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group
            name="Circle008"
            position={[-113.27, -70.961, -2.902]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={0.81}
          >
            <group
              name="Circle007"
              position={[0.519, -5.279, 67.728]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={26.655}
            >
              <mesh
                name="Circle007_BMD_AbstractGlass001_0"
                geometry={nodes.Circle007_BMD_AbstractGlass001_0.geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
            <mesh
              name="Circle008_Material009_0"
              geometry={nodes.Circle008_Material009_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group
            name="Circle009"
            position={[-143.243, -66.569, -3.078]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={0.81}
          >
            <group
              name="Circle010"
              position={[0.243, -2.186, 48.465]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[19.003, 19.003, 11.226]}
            >
              <mesh
                name="Circle010_BMD_AbstractGlass001_0"
                geometry={nodes.Circle010_BMD_AbstractGlass001_0.geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
            <mesh
              name="Circle009_Material009_0"
              geometry={nodes.Circle009_Material009_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group
            name="Circle011"
            position={[-44.462, -5.394, 23.392]}
            rotation={[-2.076, -0.681, -0.308]}
            scale={7.528}
          >
            <mesh
              name="Circle011_Material007_0"
              geometry={nodes.Circle011_Material007_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group
            name="��������������"
            position={[-81.6, -80.747, 58.289]}
            rotation={[-Math.PI / 2, 0, 0.48]}
            scale={[10.789, 18.919, 18.919]}
          >
            <group name="��������������001">
              <mesh
                name="��������������001_Material_0"
                geometry={nodes["��������������001_Material_0"].geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
            <mesh
              name="��������������_Material011_0"
              geometry={nodes["��������������_Material011_0"].geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group
            name="����������"
            position={[80.59, -82.884, 24.432]}
            rotation={[-Math.PI / 2, 0, -0.369]}
            scale={[21.043, 12.362, 12.362]}
          >
            <group
              name="Plane007"
              position={[0, -0.149, 0.018]}
              scale={[0.755, 0.127, 0.598]}
            >
              <mesh
                name="Plane007_Material014_0"
                geometry={nodes.Plane007_Material014_0.geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
            <group
              name="Plane006"
              position={[-0.612, 0.506, 0.018]}
              scale={[0.141, 0.222, 1.041]}
            >
              <mesh
                name="Plane006_Material014_0"
                geometry={nodes.Plane006_Material014_0.geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
            <mesh
              name="����������_Material013_0"
              geometry={nodes["����������_Material013_0"].geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group
            name="Plane009"
            position={[0, 18.284, 5.364]}
            scale={[74.275, 5.672, 100]}
          >
            <mesh
              name="Plane009_Material003_0"
              geometry={nodes.Plane009_Material003_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group
            name="Plane013"
            position={[42.183, -8.56, 3.409]}
            scale={[35.962, 19.895, 9.86]}
          >
            <group
              name="Plane014"
              position={[0, -0.11, 0.055]}
              scale={[0.947, 0.831, 0.313]}
            >
              <group
                name="User"
                position={[0.184, 0.041, 1.066]}
                scale={[0.319, 0.656, 3.523]}
              >
                <mesh
                  name="User_Material008_0"
                  geometry={nodes.User_Material008_0.geometry}
                  material={materials.PaletteMaterial001}
                />
              </group>
              <mesh
                name="Plane014_BMD_AbstractGlass_0"
                geometry={nodes.Plane014_BMD_AbstractGlass_0.geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
            <group
              name="Sphere003"
              position={[0.881, 0.859, -0.002]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.052, 0.188, 0.093]}
            >
              <mesh
                name="Sphere003_Material005_0"
                geometry={nodes.Sphere003_Material005_0.geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
            <mesh
              name="Plane013_Material003_0"
              geometry={nodes.Plane013_Material003_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group
            name="Plane015"
            position={[-46.228, -8.336, 2.241]}
            scale={[29.316, 14.239, 8.123]}
          >
            <group name="Plane016" position={[-0.023, -0.338, 0.163]}>
              <mesh
                name="Plane016_Material005_0"
                geometry={nodes.Plane016_Material005_0.geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
            <mesh
              name="Plane015_Material012_0"
              geometry={nodes.Plane015_Material012_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group
            name="Circle014"
            position={[-78.168, 36.087, 13.427]}
            rotation={[0, 0, -0.12]}
            scale={2.716}
          >
            <mesh
              name="Circle014_Material019_0"
              geometry={nodes.Circle014_Material019_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group
            name="Circle015"
            position={[-78.168, 36.087, 12.484]}
            rotation={[0, 0, 2.273]}
            scale={2.716}
          >
            <mesh
              name="Circle015_Material019_0"
              geometry={nodes.Circle015_Material019_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
        </group>
        <mesh
          name="Plane_Material003_0"
          geometry={nodes.Plane_Material003_0.geometry}
          material={materials.PaletteMaterial001}
          scale={[0.847, 0.468, 0.232]}
        />
        <mesh
          name="Circle013_������������_eevee_0"
          geometry={nodes["Circle013_������������_eevee_0"].geometry}
          material={materials.PaletteMaterial002}
          position={[-0.732, 0.338, 0.108]}
          scale={0.192}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/computer-transformed.glb");
