/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 database.gltf --transform 
Files: database.gltf [6.58MB] > C:\Users\Elija\Documents\database_l\database-transformed.glb [133.75KB] (98%)
Author: stefanorivera (https://sketchfab.com/stefanorivera)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/database-l-655f43f0712149798e441f015da87ba3
Title: Database L
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/database-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={
          materials.a_silver_database_server_with_blue_lights_on_a_gray_background
        }
      />
    </group>
  );
}

useGLTF.preload("/database-transformed.glb");
