/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 samsung.gltf --transform 
Files: samsung.gltf [1.79MB] > C:\Users\Elija\Documents\samsung_s21_ultra\samsung-transformed.glb [165.33KB] (91%)
Author: bendjama1986 (https://sketchfab.com/bendjama1986)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/samsung-s21-ultra-83c040b282934cf38b3f58a07c40516c
Title: Samsung S21 Ultra
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/samsung-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials.screen}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_33.geometry}
        material={materials.PaletteMaterial002}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/samsung-transformed.glb");
